# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: docs/docs/CLI.md
      - id: end-of-file-fixer
        exclude: docs/docs/CLI.md
      - id: check-yaml
      - id: check-toml
      - id: debug-statements

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black .
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [python]
      - id: lint
        name: lint
        entry: poetry run ruff . --fix
        language: system
        types: [python]
